# Generated by Django 3.1.2 on 2021-08-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210731_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=15, unique=True)),
                ('email', models.CharField(default='', max_length=30)),
                ('pass1', models.CharField(default='', max_length=20)),
                ('pass2', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
