# Generated by Django 3.2.7 on 2021-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210907_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cartjson',
            field=models.CharField(default='{}', max_length=1000),
        ),
    ]
