# Generated by Django 3.2.7 on 2021-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_userprofile_cartjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amt',
            field=models.IntegerField(default=0),
        ),
    ]
